CREATE TABLE auctions (
    id VARCHAR2(36 CHAR) NOT NULL,
    invoice_id VARCHAR2(36 CHAR) NOT NULL,
    mype_id VARCHAR2(36 CHAR) NOT NULL,
    status VARCHAR2(40 CHAR) NOT NULL,
    risk_grade VARCHAR2(20 CHAR) NOT NULL,
    invoice_amount NUMBER(19, 2) NOT NULL,
    invoice_currency VARCHAR2(3 CHAR) NOT NULL,
    fundable_amount NUMBER(19, 2),
    fundable_currency VARCHAR2(3 CHAR),
    target_amount NUMBER(19, 2),
    target_currency VARCHAR2(3 CHAR),
    current_funding_amount NUMBER(19, 2) NOT NULL,
    current_funding_currency VARCHAR2(3 CHAR) NOT NULL,
    payer_ruc VARCHAR2(20 CHAR) NOT NULL,
    payer_name VARCHAR2(200 CHAR) NOT NULL,
    due_date DATE NOT NULL,
    green_certified BOOLEAN NOT NULL,
    full_balance_outstanding_confirmed BOOLEAN NOT NULL,
    assessment_id VARCHAR2(100 CHAR),
    assessed_at TIMESTAMP(6) WITH TIME ZONE,
    accepted_quote_id VARCHAR2(36 CHAR),
    closing_transaction_id VARCHAR2(100 CHAR),
    cancellation_reason VARCHAR2(500 CHAR),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    published_at TIMESTAMP(6) WITH TIME ZONE,
    expires_at TIMESTAMP(6) WITH TIME ZONE,
    closed_at TIMESTAMP(6) WITH TIME ZONE,
    cancelled_at TIMESTAMP(6) WITH TIME ZONE,
    version NUMBER(19) NOT NULL,
    CONSTRAINT pk_auctions PRIMARY KEY (id),
    CONSTRAINT uk_auctions_invoice UNIQUE (invoice_id),
    CONSTRAINT ck_auctions_invoice_currency CHECK (invoice_currency IN ('PEN', 'USD')),
    CONSTRAINT ck_auctions_fundable_currency CHECK (fundable_currency IS NULL OR fundable_currency IN ('PEN', 'USD')),
    CONSTRAINT ck_auctions_target_currency CHECK (target_currency IS NULL OR target_currency IN ('PEN', 'USD')),
    CONSTRAINT ck_auctions_current_currency CHECK (current_funding_currency IN ('PEN', 'USD')),
    CONSTRAINT ck_auctions_risk_grade CHECK (risk_grade IN ('A', 'B', 'C', 'UNDER_EVALUATION')),
    CONSTRAINT ck_auctions_status CHECK (
        status IN ('PENDING_VERIFICATION_RISK', 'DRAFT', 'PUBLISHED', 'FUNDING', 'FULLY_FUNDED', 'CLOSED', 'EXPIRED', 'CANCELLED')
    )
);

CREATE TABLE auction_financial_quotes (
    id VARCHAR2(36 CHAR) NOT NULL,
    auction_id VARCHAR2(36 CHAR) NOT NULL,
    status VARCHAR2(20 CHAR) NOT NULL,
    pricing_version VARCHAR2(40 CHAR) NOT NULL,
    risk_grade VARCHAR2(20 CHAR) NOT NULL,
    currency VARCHAR2(3 CHAR) NOT NULL,
    term_days NUMBER(10) NOT NULL,
    fundable_amount NUMBER(19, 2) NOT NULL,
    investor_tea NUMBER(19, 12) NOT NULL,
    investor_term_rate NUMBER(19, 12) NOT NULL,
    funding_target NUMBER(19, 2) NOT NULL,
    investor_gross_profit NUMBER(19, 2) NOT NULL,
    platform_monthly_fee_rate NUMBER(19, 12) NOT NULL,
    platform_fee_base NUMBER(19, 2) NOT NULL,
    platform_fee_tax_rate NUMBER(19, 12) NOT NULL,
    platform_fee_tax NUMBER(19, 2) NOT NULL,
    platform_fee_total NUMBER(19, 2) NOT NULL,
    mype_advance NUMBER(19, 2) NOT NULL,
    mype_total_cost NUMBER(19, 2) NOT NULL,
    mype_tcea NUMBER(19, 12) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    valid_until TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    accepted_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT pk_auction_financial_quotes PRIMARY KEY (id),
    CONSTRAINT fk_quotes_auction FOREIGN KEY (auction_id) REFERENCES auctions (id),
    CONSTRAINT ck_quotes_status CHECK (status IN ('ACTIVE', 'ACCEPTED', 'SUPERSEDED', 'EXPIRED')),
    CONSTRAINT ck_quotes_risk_grade CHECK (risk_grade IN ('A', 'B', 'C')),
    CONSTRAINT ck_quotes_currency CHECK (currency IN ('PEN', 'USD'))
);

CREATE TABLE partitions (
    id VARCHAR2(36 CHAR) NOT NULL,
    auction_id VARCHAR2(36 CHAR) NOT NULL,
    investor_id VARCHAR2(36 CHAR) NOT NULL,
    investment_amount NUMBER(19, 2) NOT NULL,
    investment_currency VARCHAR2(3 CHAR) NOT NULL,
    participation_percentage NUMBER(19, 8) NOT NULL,
    return_rate NUMBER(19, 8) NOT NULL,
    expected_return_amount NUMBER(19, 2) NOT NULL,
    expected_return_currency VARCHAR2(3 CHAR) NOT NULL,
    actual_return_amount NUMBER(19, 2),
    actual_return_currency VARCHAR2(3 CHAR),
    status VARCHAR2(20 CHAR) NOT NULL,
    purchased_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    paid_at TIMESTAMP(6) WITH TIME ZONE,
    investment_transaction_id VARCHAR2(100 CHAR) NOT NULL,
    payment_transaction_id VARCHAR2(100 CHAR),
    version NUMBER(19) NOT NULL,
    CONSTRAINT pk_partitions PRIMARY KEY (id),
    CONSTRAINT fk_partitions_auction FOREIGN KEY (auction_id) REFERENCES auctions (id),
    CONSTRAINT uk_partitions_transaction UNIQUE (investment_transaction_id),
    CONSTRAINT ck_partitions_investment_currency CHECK (investment_currency IN ('PEN', 'USD')),
    CONSTRAINT ck_partitions_expected_currency CHECK (expected_return_currency IN ('PEN', 'USD')),
    CONSTRAINT ck_partitions_actual_currency CHECK (actual_return_currency IS NULL OR actual_return_currency IN ('PEN', 'USD')),
    CONSTRAINT ck_partitions_status CHECK (status IN ('ACTIVE', 'PAID', 'DEFAULTED', 'CANCELLED'))
);

CREATE INDEX ix_auctions_marketplace ON auctions (status, expires_at);
CREATE INDEX ix_quotes_auction ON auction_financial_quotes (auction_id, status);
CREATE INDEX ix_partitions_auction ON partitions (auction_id, status);
